### ISSUE TITLE
[KVCache (Vineyard)]Are there 3 or more  replicas's deployment distributed KV test cases？

### ISSUE THREAD

**Issue by ying2025** [vllm-project/aibrix#1012]
### 🚀 Feature Description and Motivation

I hope to have 3 or more replicas's deployment distributed KV test cases, and how I watch kv cache imporve.

### Use Case

This [case](https://aibrix.readthedocs.io/latest/features/distributed-kv-cache.html) only have one kv cache pod.

**Comment by ying2025** [comment]
@Jeffwan Otherwise, the KVCache crd create the etcd with `aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vineyardd:20241120` image instead of the mirror of etcd itself, and what does it use it for?
```
apiVersion: orchestration.aibrix.ai/v1alpha1
kind: KVCache
metadata:
  name: aibrix-kvcache-llama-3-8b-instruct
  namespace: default
  annotations:
    kvcache.orchestration.aibrix.ai/pod-affinity-workload: llama-3-8b-instruct
    kvcache.orchestration.aibrix.ai/pod-anti-affinity: "true"
    kvcache.orchestration.aibrix.ai/node-affinity-gpu-type: NVIDIA-L20
spec:
  replicas: 1
  service:
    type: ClusterIP
    port: 9600
  cacheSpec:
    image: aibrix-container-registry-cn-beijing.cr.volces.com/aibrix/vineyardd:20241120
    imagePullPolicy: IfNotPresent
    cpu: "4000m"
    memory: 72Gi
```
