### ISSUE TITLE
"Startup probe failed" bug when deploy base model

### ISSUE THREAD

**Issue by OrdinaryCrazy** [vllm-project/aibrix#1054]
### 🐛 Describe the bug

I met a "Startup probe failed" bug when deploy base model following the QuickStart tutorial:
```bash
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  5m31s             default-scheduler  Successfully assigned default/deepseek-r1-distill-llama-8b-5cc594fd46-hg5rw to minikube
  Normal   Pulling    5m23s             kubelet            Pulling image "vllm/vllm-openai:v0.7.1"
  Normal   Pulled     19s               kubelet            Successfully pulled image "vllm/vllm-openai:v0.7.1" in 4m47.129s (5m3.623s including waiting). Image size: 16525161745 bytes.
  Normal   Created    19s               kubelet            Created container: vllm-openai
  Normal   Started    18s               kubelet            Started container vllm-openai
  Warning  Unhealthy  3s (x3 over 13s)  kubelet            Startup probe failed: Get "http://10.244.0.13:8000/health": dial tcp 10.244.0.13:8000: connect: connection refused
```

### Steps to Reproduce

1. Tried both ways below to start AIbrix in minikube
```bash
kubectl create -f https://github.com/vllm-project/aibrix/releases/download/v0.2.1/aibrix-dependency-v0.2.1.yaml
kubectl create -f https://github.com/vllm-project/aibrix/releases/download/v0.2.1/aibrix-core-v0.2.1.yaml
```
and
```bash
kubectl create -k config/dependency
kubectl create -k config/default
```
2. Copied _model.yaml_ from QuickStart tutorial
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    model.aibrix.ai/name: deepseek-r1-distill-llama-8b # Note: The label value `model.aibrix.ai/name` here must match with the service name.
    model.aibrix.ai/port: "8000"
  name: deepseek-r1-distill-llama-8b
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      model.aibrix.ai/name: deepseek-r1-distill-llama-8b
  template:
    metadata:
      labels:
        model.aibrix.ai/name: deepseek-r1-distill-llama-8b
    spec:
      containers:
        - command:
            - python3
            - -m
            - vllm.entrypoints.openai.api_server
            - --host
            - "0.0.0.0"
            - --port
            - "8000"
            - --uvicorn-log-level
            - warning
            - --model
            - deepseek-ai/DeepSeek-R1-Distill-Llama-8B
            - --served-model-name
            # Note: The `--served-model-name` argument value must also match the Service name and the Deployment label `model.aibrix.ai/name`
            - deepseek-r1-distill-llama-8b
            - --max-model-len
            - "12288" # 24k length, this is to avoid "The model's max seq len (131072) is larger than the maximum number of tokens that can be stored in KV cache" issue.
          image: vllm/vllm-openai:v0.7.1
          imagePullPolicy: IfNotPresent
          name: vllm-openai
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            failureThreshold: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            failureThreshold: 5
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          startupProbe:
            httpGet:
              path: /health
              port: 8000
              scheme: HTTP
            failureThreshold: 30
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1

---

apiVersion: v1
kind: Service
metadata:
  labels:
    model.aibrix.ai/name: deepseek-r1-distill-llama-8b
    prometheus-discovery: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: deepseek-r1-distill-llama-8b # Note: The Service name must match the label value `model.aibrix.ai/name` in the Deployment
  namespace: default
spec:
  ports:
    - name: serve
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    model.aibrix.ai/name: deepseek-r1-distill-llama-8b
  type: ClusterIP
```
3. Applied _model.yaml_
```bash
kubectl apply -f model.yaml
```
4. See bug:
```bash
(aibrix) ubuntu@104-171-203-5:~/aibrix$ kubectl get pods
NAME                                            READY   STATUS             RESTARTS        AGE
deepseek-r1-distill-llama-8b-5cc594fd46-hg5rw   0/1     CrashLoopBackOff   5 (2m30s ago)   13m
(aibrix) ubuntu@104-171-203-5:~/aibrix$ kubectl describe pod deepseek-r1-distill-llama-8b-5cc594fd46-hg5rw
Name:             deepseek-r1-distill-llama-8b-5cc594fd46-hg5rw
Namespace:        default
Priority:         0
Service Account:  default
Node:             minikube/192.168.49.2
Start Time:       Tue, 06 May 2025 17:37:06 +0000
Labels:           model.aibrix.ai/name=deepseek-r1-distill-llama-8b
                  pod-template-hash=5cc594fd46
Annotations:      <none>
Status:           Running
IP:               10.244.0.13
IPs:
  IP:           10.244.0.13
Controlled By:  ReplicaSet/deepseek-r1-distill-llama-8b-5cc594fd46
Containers:
  vllm-openai:
    Container ID:  docker://8df64776f9c7157424ec5522ed5124120f01da1a536ef9428e4ba0e3c4ad7397
    Image:         vllm/vllm-openai:v0.7.1
    Image ID:      docker-pullable://vllm/vllm-openai@sha256:9cd69b577cf26df32aceb74577ea7f6749618a72e630f654ecb10dbfb23e3de4
    Port:          8000/TCP
    Host Port:     0/TCP
    Command:
      python3
      -m
      vllm.entrypoints.openai.api_server
      --host
      0.0.0.0
      --port
      8000
      --uvicorn-log-level
      warning
      --model
      deepseek-ai/DeepSeek-R1-Distill-Llama-8B
      --served-model-name
      deepseek-r1-distill-llama-8b
      --max-model-len
      12288
    State:          Running
      Started:      Tue, 06 May 2025 17:42:11 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      nvidia.com/gpu:  1
    Requests:
      nvidia.com/gpu:  1
    Liveness:          http-get http://:8000/health delay=0s timeout=1s period=5s #success=1 #failure=3
    Readiness:         http-get http://:8000/health delay=0s timeout=1s period=5s #success=1 #failure=5
    Startup:           http-get http://:8000/health delay=0s timeout=1s period=5s #success=1 #failure=30
    Environment:       <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cs8dn (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  kube-api-access-cs8dn:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    Optional:                false
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  5m31s             default-scheduler  Successfully assigned default/deepseek-r1-distill-llama-8b-5cc594fd46-hg5rw to minikube
  Normal   Pulling    5m23s             kubelet            Pulling image "vllm/vllm-openai:v0.7.1"
  Normal   Pulled     19s               kubelet            Successfully pulled image "vllm/vllm-openai:v0.7.1" in 4m47.129s (5m3.623s including waiting). Image size: 16525161745 bytes.
  Normal   Created    19s               kubelet            Created container: vllm-openai
  Normal   Started    18s               kubelet            Started container vllm-openai
  **Warning  Unhealthy  3s (x3 over 13s)  kubelet            Startup probe failed: Get "http://10.244.0.13:8000/health": dial tcp 10.244.0.13:8000: connect: connection refused**
``` 

### Expected behavior

Successfully deploy the base model (can be used seamlessly as vllm server).

### Environment

* minikube:
```bash
minikube start --driver=docker --container-runtime=docker --gpus=all --cpus=8 --memory=16g
minikube tunnel
```
```bash
(aibrix) ubuntu@104-171-203-5:~/aibrix$ minikube version
minikube version: v1.35.0
commit: dd5d320e41b5451cdf3c01891bc4e13d189586ed-dirty
```
* Lambda Lab GPU Instance: `gpu_8x_v100`

**Comment by OrdinaryCrazy** [comment]
# Issue Root:

* The GPU used `Tesla V100-SXM2-16GB` has too small memory to deploy deepseek model with settings in _model.yaml_ 

# Debug:
* I tried to deploy the same model with vllm sever and got more clear feedback
```bash
vllm serve deepseek-ai/DeepSeek-R1-Distill-Llama-8B --dtype=half --max-model-len "12288"
...
ERROR 05-06 18:20:49 [engine.py:448] CUDA out of memory. Tried to allocate 96.00 MiB. GPU 0 has a total capacity of 15.77 GiB of which 64.44 MiB is free. Including non-PyTorch memory, this process has 15.70 GiB memory in use. Of the allocated memory 15.33 GiB is allocated by PyTorch, and 8.97 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

# Resolution:
* Move to another GPU instance with 32GB+ Memory.

**OR**

* Since I just need a chat model which does not have to be deepseek, so I changed _model.yaml_ to deploy a QWEN2.5 model

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    model.aibrix.ai/name: qwen25-15b-instruct # Note: The label value `model.aibrix.ai/name` here must match with the service name.
    model.aibrix.ai/port: "8000"
  name: qwen25-15b-instruct
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      model.aibrix.ai/name: qwen25-15b-instruct
  template:
    metadata:
      labels:
        model.aibrix.ai/name: qwen25-15b-instruct
    spec:
      containers:
        - command:
            - python3
            - -m
            - vllm.entrypoints.openai.api_server
            - --host
            - "0.0.0.0"
            - --port
            - "8000"
            - --uvicorn-log-level
            - warning
            - --model
            - Qwen/Qwen2.5-1.5B-Instruct
            - --dtype
            - half
            - --served-model-name
            # Note: The `--served-model-name` argument value must also match the Service name and the Deployment label `model.aibrix.ai/name`
            - qwen25-15b-instruct
          image: vllm/vllm-openai:v0.7.1
          imagePullPolicy: IfNotPresent
          name: vllm-openai
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              nvidia.com/gpu: "1"
            requests:
              nvidia.com/gpu: "1"
              
---

apiVersion: v1
kind: Service
metadata:
  labels:
    model.aibrix.ai/name: qwen25-15b-instruct
    prometheus-discovery: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
  name: qwen25-15b-instruct # Note: The Service name must match the label value `model.aibrix.ai/name` in the Deployment
  namespace: default
spec:
  ports:
    - name: serve
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    model.aibrix.ai/name: qwen25-15b-instruct
  type: ClusterIP
```
```bash
(aibrix) ubuntu@104-171-203-5:~/aibrix$ kubectl describe pods qwen25-15b-instruct-6c9598f67f-c7mcl
Name:             qwen25-15b-instruct-6c9598f67f-c7mcl
Namespace:        default
Priority:         0
Service Account:  default
Node:             minikube/192.168.49.2
Start Time:       Tue, 06 May 2025 18:34:10 +0000
Labels:           model.aibrix.ai/name=qwen25-15b-instruct
                  pod-template-hash=6c9598f67f
Annotations:      <none>
Status:           Running
IP:               10.244.0.16
IPs:
  IP:           10.244.0.16
Controlled By:  ReplicaSet/qwen25-15b-instruct-6c9598f67f
Containers:
  vllm-openai:
    Container ID:  docker://1bcabb532af7eea828cb23a10aa799108ffb989eabfb51c4fbc541b5dc3dc0ef
    Image:         vllm/vllm-openai:v0.7.1
    Image ID:      docker-pullable://vllm/vllm-openai@sha256:9cd69b577cf26df32aceb74577ea7f6749618a72e630f654ecb10dbfb23e3de4
    Port:          8000/TCP
    Host Port:     0/TCP
    Command:
      python3
      -m
      vllm.entrypoints.openai.api_server
      --host
      0.0.0.0
      --port
      8000
      --uvicorn-log-level
      warning
      --model
      Qwen/Qwen2.5-1.5B-Instruct
      --dtype
      half
      --served-model-name
      qwen25-15b-instruct
    State:          Running
      Started:      Tue, 06 May 2025 18:34:11 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      nvidia.com/gpu:  1
    Requests:
      nvidia.com/gpu:  1
    Environment:       <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-8rpms (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       True 
  ContainersReady             True 
  PodScheduled                True 
Volumes:
  kube-api-access-8rpms:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    Optional:                false
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type    Reason     Age    From               Message
  ----    ------     ----   ----               -------
  Normal  Scheduled  4m54s  default-scheduler  Successfully assigned default/qwen25-15b-instruct-6c9598f67f-c7mcl to minikube
  Normal  Pulled     4m43s  kubelet            Container image "vllm/vllm-openai:v0.7.1" already present on machine
  Normal  Created    4m43s  kubelet            Created container: vllm-openai
  Normal  Started    4m43s  kubelet            Started container vllm-openai
(aibrix) ubuntu@104-171-203-5:~/aibrix$ kubectl get pods
NAME                                   READY   STATUS    RESTARTS   AGE
qwen25-15b-instruct-6c9598f67f-c7mcl   1/1     Running   0          4m55s
```

# Summary 
* You need a 32GB+ GPU to run the QuickStart base model.
* More clear and direct debug messages are expected when deployment is failed.
