### ISSUE TITLE
Isn't multi-node inference a type of high availability mode?

### ISSUE THREAD

**Issue by carapuces** [vllm-project/aibrix#1157]
### 🚀 Feature Description and Motivation

I created a Ray cluster with 1 head node and 3 workers using RayClusterFleet. However, when I delete a worker pod, the entire cluster gets reconstructed, and the remaining pods also restart. I'm unsure if this is due to my test parameters or if Aibrix doesn't currently support high availability for multi-node inference. Below is the YAML file I used to create the RayClusterFleet:
```
apiVersion: orchestration.aibrix.ai/v1alpha1
kind: RayClusterFleet
metadata:
  name: qwen-coder-ray-instruct
  namespace: aibrix-system
  labels:
    app.kubernetes.io/name: aibriwx
    app.kubernetes.io/managed-by: kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      model.aibrix.ai/name: qwen-coder-ray-instruct
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        model.aibrix.ai/name: qwen-coder-ray-instruct
      annotations:
        ray.io/overwrite-container-cmd: "true"
    spec:
      rayVersion: "2.10.0"
      headGroupSpec:
        rayStartParams:
          dashboard-host: "0.0.0.0"
        template:
          metadata:
            namespace: aibrix-system
            labels:
              model.aibrix.ai/name: qwen-coder-ray-instruct
          spec:
            volumes:
              - name: models
                hostPath:
                  path: /ai/aibrix/aibrix/models
                  type: Directory
            containers:
              - name: ray-head
                image: docker.inspur.com:5000/vllm/vllm-openai:v0.7.1
                command: ["/bin/bash", "-c"]
                args:
                  - >
                    ulimit -n 65536 &&
                    echo "[INFO] Starting Ray head node..." &&
                    eval "$KUBERAY_GEN_RAY_START_CMD" &

                    echo "[INFO] Waiting for Ray dashboard to be ready..." &&
                    until curl --max-time 5 --fail http://127.0.0.1:8265 > /dev/null 2>&1; do
                      echo "[WAITING] $(date -u +'%Y-%m-%dT%H:%M:%SZ') - Ray dashboard not ready yet...";
                      sleep 2;
                    done &&
                    echo "[SUCCESS] Ray dashboard is available!" &&

                    vllm serve /models/Qwen2.5-Coder-1.5B-Instruct \
                      --served-model-name qwen-coder-ray-instruct \
                      --tensor-parallel-size 1 \
                      --distributed-executor-backend ray \
                      --host 0.0.0.0 \
                      --port 8000 \
                      --dtype half
                ports:
                  - containerPort: 6379
                    name: gcs-server
                  - containerPort: 8265
                    name: dashboard
                  - containerPort: 10001
                    name: client
                  - containerPort: 8000
                    name: service
                resources:
                  limits:
                    cpu: "4"
                    nvidia.com/gpu: 1
                  requests:
                    cpu: "4"
                    nvidia.com/gpu: 1
                volumeMounts:
                  - mountPath: /models
                    name: models
              - name: aibrix-runtime
                image: docker.inspur.com:5000/aibrix/runtime:v0.3.0
                command:
                  - aibrix_runtime
                  - --port
                  - "8080"
                env:
                  - name: INFERENCE_ENGINE
                    value: vllm
                  - name: INFERENCE_ENGINE_ENDPOINT
                    value: http://localhost:8000
                  - name: PYTORCH_CUDA_ALLOC_CONF
                    value: "expandable_segments:True"
                ports:
                  - containerPort: 8080
                    protocol: TCP
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8080
                  initialDelaySeconds: 3
                  periodSeconds: 2
                readinessProbe:
                  httpGet:
                    path: /ready
                    port: 8080
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: "1"
                  requests:
                    cpu: "1"
                volumeMounts:
                  - mountPath: /models
                    name: models
      workerGroupSpecs:
        - groupName: small-group-1
          replicas: 3
          minReplicas: 1
          maxReplicas: 1
          rayStartParams: {}
          template:
            metadata:
              namespace: aibrix-system
              labels:
                model.aibrix.ai/name: qwen-coder-ray-instruct
            spec:
              volumes:
                - name: models
                  hostPath:
                    path: /ai/aibrix/aibrix/models
                    type: Directory
              containers:
                - name: ray-worker
                  image: docker.inspur.com:5000/vllm/vllm-openai:v0.7.1
                  env:
                    - name: MY_POD_IP
                      valueFrom:
                        fieldRef:
                          fieldPath: status.podIP
                  command: [ "/bin/bash", "-c" ]
                  args:
                    - >
                      ulimit -n 65536 &&
                      eval "$KUBERAY_GEN_RAY_START_CMD --node-ip-address=$MY_POD_IP" &&
                      tail -f /dev/null
                  lifecycle:
                    preStop:
                      exec:
                        command: [ "/bin/sh", "-c", "ray stop" ]
                  resources:
                    limits:
                      cpu: "4"
                      nvidia.com/gpu: 1
                    requests:
                      cpu: "4"
                      nvidia.com/gpu: 1
                  volumeMounts:
                    - mountPath: /models
                      name: models


---

apiVersion: v1
kind: Service
metadata:
  name: qwen-coder-ray-instruct
  namespace: aibrix-system
  labels:
    model.aibrix.ai/name: qwen-coder-ray-instruct
    prometheus-discovery: "true"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    model.aibrix.ai/name: qwen-coder-ray-instruct
  ports:
    - name: serve
      port: 8000
      protocol: TCP
      targetPort: 8000
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080

---

apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: qwen-coder-ray-instruct-router
  namespace: aibrix-system
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: aibrix-eg
      namespace: aibrix-system
  rules:
    - backendRefs:
        - group: ""
          kind: Service
          name: qwen-coder-ray-instruct
          namespace: aibrix-system
          port: 8000  # or 8000 if you're not using the runtime sidecar
          weight: 1
      matches:
        - headers:
            - name: model
              type: Exact
              value: qwen-coder-ray-instruct
          path:
            type: PathPrefix
            value: /v1/completions
        - headers:
            - name: model
              type: Exact
              value: qwen-coder-ray-instruct
          path:
            type: PathPrefix
            value: /v1/chat/completions
      timeouts:
        request: 120s
```

### Use Case

high availability for multi-node inference
