### ISSUE TITLE
[httproute] add  /v1/version is not found

### ISSUE THREAD

**Issue by ying2025** [vllm-project/aibrix#1175]
### 🚀 Feature Description and Motivation

 I add `/v1/version` method, and it's not found, where is it block? I add the`/v1/models` method, it return all the models, and I find it visit `aibrix-metadata-service` service.What should I do if I want use `/v1/version` and `/v1/models`

### Use Case

```
    matches:
    - headers:
      - name: model
        type: Exact
        value: nodetest128-w73sg65c
      path:
        type: PathPrefix
        value: /v1/completions
    - headers:
      - name: model
        type: Exact
        value: nodetest128-w73sg65c
      path:
        type: PathPrefix
        value: /v1/chat/completions
    - headers:
      - name: model
        type: Exact
        value: nodetest128-w73sg65c
      path:
        type: PathPrefix
        value: /v1/models
    - headers:
      - name: model
        type: Exact
        value: nodetest128-w73sg65c
      path:
        type: PathPrefix
        value: /v1/version
```

**Comment by varungup90** [comment]
You need to create a [reserved route](https://github.com/vllm-project/aibrix/blob/main/config/gateway/gateway-plugin/gateway-plugin.yaml#L120) for /v1/version that will have backend ref as aibrix-metadata-service and implementation [here](https://github.com/vllm-project/aibrix/blob/main/pkg/metadata/handlers.go#L54).

**Comment by ying2025** [comment]
> aibrix-metadata-service

aibrix-metadata-service return all the models, and it lack of model related information. Do you mean forwarding through aibrix metadata service to the corresponding interface of the specific pod?

**Comment by Xunzhuo** [comment]
@varungup90 we should consider creating platform related CR, not surfacing end-user

**Comment by ying2025** [comment]
Otherwise, for some requests in non-standard OpenAPI formats maybe also consider compatibility

**Comment by varungup90** [comment]
> @varungup90 we should consider creating platform related CR, not surfacing end-user

That's my goal to provide pointers to add /v1/version.

@ying2025 To clarify, /v1/version is not supported right now by AIBrix. If you are interested please help in adding it, shared some pointers above to help in writing code.

**Comment by ying2025** [comment]
> > [@varungup90](https://github.com/varungup90) we should consider creating platform related CR, not surfacing end-user
> 
> That's my goal to provide pointers to add /v1/version.
> 
> [@ying2025](https://github.com/ying2025) To clarify, /v1/version is not supported right now by AIBrix. If you are interested please help in adding it, shared some pointers above to help in writing code.
ok, It's good.

**Comment by ying2025** [comment]
@varungup90 
Firstly, for the standard API interface, we can add a tag in the annotation to identify the methods that the user wishes to have, and inject these methods into rules.backendRefs when we create httproute, such as the following.Then we can `curl 
 -X GET http://envoy ip:port/version -H 'model  nodetest133-fxtdep7q'`  get the version.For some non-standard OpenAPI, we  
can define some struct in the code or in the configmap.
```
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: nodetest133-fxtdep7q
      namespace: test
      port: 8000
      weight: 1
    matches:
    - headers:
      - name: model
        type: Exact
        value: nodetest133-fxtdep7q
      path:
        type: PathPrefix
        value: /v1/completions
    - headers:
      - name: model
        type: Exact
        value: nodetest133-fxtdep7q
      path:
        type: PathPrefix
        value: /v1/chat/completions
    - headers:
      - name: model
        type: Exact
        value: nodetest133-fxtdep7q
      path:
        type: PathPrefix
        value: /v1/models
    - headers:
      - name: model
        type: Exact
        value: nodetest133-fxtdep7q
      path:
        type: PathPrefix
        value: /version
```

**Comment by varungup90** [comment]
We need to create another httproute for each model deployment and this httproute does not have an associated envoyextensiopolicy so it will directly go to model deployment. Need to extend [model router controller](https://github.com/vllm-project/aibrix/blob/main/pkg/controller/modelrouter/modelrouter_controller.go) to create another httproute to support /version and /metrics. 

Few things to consider are
- Results returned will be from any random pod, can you check if envoy httproute has support to target specific pod by name or IP via header.
- Aibrix has envoy patch policy to target specific pod for request forwarding, but for that it will need implementation changes to handle /version request path, similar to what we have for /v1/chat/completions. I am little hesistant right now to do so without having more user feedback and design work.
- For now what I will recommend, you can use sample httproute to modify for your env to unblock yourself. Making controller changes is also easy, if you want you can start the PR + apply local controller build for your env. To merge the PR, will have to do more due diligence.

```
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: facebook-opt-125m-direct-endpoint-router
  namespace: aibrix-system
spec:
  parentRefs:
    - name: aibrix-eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: facebook-opt-125m
      namespace: default
      port: 8000
      weight: 1
    matches:
    - headers:
      - name: model
        type: Exact
        value: facebook-opt-125m
      path:
        type: PathPrefix
        value: /version
    - headers:
      - name: model
        type: Exact
        value: facebook-opt-125m
      path:
        type: PathPrefix
        value: /metrics
    timeouts:
      request: 120s
```

<img width="800" alt="Image" src="https://github.com/user-attachments/assets/ca05cb04-609e-4209-8471-6cb6cbe7dc8f" />
