### ISSUE TITLE
Make PodAutoscaler Parameters Configurable

### ISSUE THREAD

**Issue by kr11** [vllm-project/aibrix#406]
## Background and Motivation

Currently, most of the configuration parameters for KPA and APA are hard-coded in functions like `NewKpaAutoscaler`. This approach lacks flexibility. To improve the flexibility and customization options for KPA and APA, we propose making these configuration parameters configurable via the `pa.yaml` file or a configmap.

## Proposed Changes

We categorize the related configuration parameters into three parts:

1. **Controller-level Parameters**
   These are global parameters that are suitable to be configured via a configmap.
   ```yaml
   resyncInterval: 10s
   ```

2. **Common PodAutoscaler Parameters**
   These parameters are shared by both KPA and APA.
   ```yaml
   MaxScaleUpRate:   2     # Scale up rate of 200%, allowing rapid scaling
   MaxScaleDownRate: 2     # Scale down rate of 50%, for more gradual reduction
   ScalingMetric:    "CPU" # Metric used for scaling, here set to CPU utilization
   TargetValue:      30.0  # Target CPU utilization set at 10%
   TotalValue:       100.0 # Total CPU utilization capacity for pods is 100%
   ```

3. **Autoscaler-specific Parameters**
   - KPA:
     ```yaml
     TargetBurstCapacity: 2.0              # Target burst capacity to handle sudden spikes
     ActivationScale:     1                # Initial scaling factor upon activation
     PanicThreshold:      2.0              # Panic threshold set at 200% to trigger rapid scaling
     StableWindow:        60s              # Time window to stabilize before altering scale
     ScaleDownDelay:      30m              # Delay before scaling down to avoid flapping
     ```
   - APA:
     ```yaml
     UpFluctuationTolerance: 0.1    # Threshold before scaling up
     DownFluctuationTolerance: 0.1  # Threshold before scaling down
     ```

## related pr:
We have created a pull request #409  to set the latter two parts of parameters via `pa.yaml`. 

## New Issue:
See more detailed in #410
However, we have discovered that some parameters are stateful, such as the three parts of KPAScaler: `panic_window`, `stable_window`, and `delay_windows`. These three parts are only initialized when the controller starts.

The `reconcile()` function updates the `KpaScalingContext` periodically but does not reset these three parts. As a result, `apply -f pa.yaml` may fail to take effect on these stateful parameters.

I think we can address this issue in another PR later, together with more information from the ongoing work issue #407  and issue #349. part 1.
