### ISSUE TITLE
Replace our cloned 3rd-party yamls with helm charts

### ISSUE THREAD

**Issue by Jeffwan** [vllm-project/aibrix#452]
### 🚀 Feature Description and Motivation

currently, we manage envoy-gateway and kuberay manifest in a downstream way. It could be outdated or lose track in future. Kustomize now supports to include helm charts in the manifest file. If this way works fine and we can easily customize the image we'd like to use (we did have some patch in the image). then we deprecated the previous naive way.

```
# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
- name: mergestat
  repo: https://helm.mergestat.com/
  releaseName: mergestat
  namespace: admin
  version: 0.1.0
  valuesFile: values.yaml
```

> Note: check the kustomize version. kubectl kustomize might not provide such features comparing to separate kustomize cli.  (higher version)
