### ISSUE TITLE
Adding PodAutoscaler ScalingDown to 0 Handling 

### ISSUE THREAD

**Issue by nwangfw** [vllm-project/aibrix#481]
### 🐛 Describe the bug

We currently configure the yaml spec to ensure the number of replicas of a workload is within a range.
```
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: simulator-llama2-7b-a100
  minReplicas: 1
  maxReplicas: 10
```
If a user doesn't configure it correctly and configures minReplicas to 0, the workload will not initiate and cause an error at Gateway (e.g., the Gateway will not be able to find a working pod). Our podAutoscaler scaling strategy should handle this case and ensure the minReplica is at least 1.
