### ISSUE TITLE
Support different lora adapter artifact registry

### ISSUE THREAD

**Issue by Jeffwan** [vllm-project/aibrix#49]
### 🚀 Feature Description and Motivation

```
apiVersion: model.aibrix.ai/v1alpha1
kind: ModelAdapter
metadata:
  name: text2sql-lora-1
  namespace: default
spec:
  baseModel: llama2-70b
  podSelector:
    matchLabels:
      model.aibrix.ai: llama2-70b
  additionalConfig:
    # could be model artifact etc.
    modelArtifact: yard1/llama-2-7b-sql-lora-test
  schedulerName: default-model-adapter-scheduler
```

Currently,  we just use a simple `modelArtifact` key. this is kind of simple and it only support two "registries"

- local: it has to be absolute path accessible from the container
- huggingface repo id

This is definitely not enough. we need better structure to support more artifact registry and associated authN credentials

### Use Case

1. Support S3 or other registries
