### ISSUE TITLE
autoscaler failed to fetch https endpoint

### ISSUE THREAD

**Issue by Jeffwan** [vllm-project/aibrix#528]
### 🚀 Feature Description and Motivation

Even we allow to configure `https` from custom resource side, it fails to fetch the http endpoint due to the certificate issue.

![image](https://github.com/user-attachments/assets/17daa9ee-6e88-43cb-a516-01afa84748a9)

We need to use insecure client to scrape the metrics instead

## Processure

```
apiVersion: autoscaling.aibrix.ai/v1alpha1
kind: PodAutoscaler
metadata:
  name: metric-server-autoscaler
  namespace: kube-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metrics-server
  minReplicas: 1
  maxReplicas: 4
  metricsSources:
  - metricSourceType: "pod"
    protocolType: "https"
    port: "4443"
    targetMetric: "apiserver_audit_requests_event_total"
    targetValue: "5"
  scalingStrategy: "KPA"
```

test on local docker for desktop

```
kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/high-availability-1.21+.yaml
```

```
kubectl edit deployment metric-server -n kube-system
```
remove `spec.affinity` and update `replicas` to 1

![image](https://github.com/user-attachments/assets/1e2dd6a2-e7fc-4c79-ad73-f6bdbf38a328)
