### ISSUE TITLE
Support lora absolute path

### ISSUE THREAD

**Issue by Jeffwan** [vllm-project/aibrix#555]
### 🚀 Feature Description and Motivation

This way doesn't work well, it can not pass the model adapter artifact protocol validation
```
apiVersion: model.aibrix.ai/v1alpha1
kind: ModelAdapter
metadata:
  name: lora-1
  namespace: default
  labels:
    model.aibrix.ai/name: "lora-1"
    model.aibrix.ai/port: "8000"
spec:
  baseModel: llama2-70b
  podSelector:
    matchLabels:
      model.aibrix.ai/name: llama2-70b
"tutorial/lora/model_adapter.yaml" 34L, 802B
    matchLabels:
      model.aibrix.ai/name: llama2-70b
  artifactURL: /test/llama-2-7b-sql-lora-test
  schedulerName: default
```

![image](https://github.com/user-attachments/assets/cc005813-ad4c-44b1-b2f8-7484cd8ce1b0)

### Use Case

to handle TOS bucket issue
