### ISSUE TITLE
Examples should come with health and readiness checks

### ISSUE THREAD

**Issue by Jeffwan** [vllm-project/aibrix#685]
### 🚀 Feature Description and Motivation

Currently, the pod becomes ready immediately, however, the application loading time is still long, at this moment, request to the model server will fail. We used to have such settings but we recently remove them for simplicity. 

### Use Case

for stable deployment

**Comment by vivek-orbi** [comment]
**I'm willing to take this up.**

Based on the samples, here's my understanding of the solution for your requirement:

1. Problem: Pod becomes ready immediately while the application/model is still loading, causing failed requests.
2. Proposed Solution: Implement health and readiness probes with appropriate delays:
```
livenessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 120
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /health
    port: 8000
  initialDelaySeconds: 120
  periodSeconds: 5
  timeoutSeconds: 1
  failureThreshold: 5
```

3. Key Settings:

- 120 seconds initial delay to account for model loading time
- Same /health endpoint for both probes
- Different failure thresholds (3 for liveness, 5 for readiness)

Is my understanding correct that:

1. Your main issue is premature traffic routing before the model is fully loaded?
2. The 120-second initial delay would be sufficient for your model loading time?
3. You're using a setup similar to the samples (vLLM or similar serving framework)?

Please let me know if any of these assumptions need adjustment for your specific use case.
