### ISSUE TITLE
Pod scale success,aibrix-controller-manager failed to parse metrics

### ISSUE THREAD

**Issue by ying2025** [vllm-project/aibrix#852]
### 🚀 Feature Description and Motivation

I0312 11:29:43.536240       7 podautoscaler_controller.go:669] "Scaler not found, creating new scaler" metricKey="prdsafe/qwen-coder-1-5b-instruct" type="KPA"
I0312 11:29:43.536318       7 podautoscaler_controller.go:687] "New scaler added to AutoscalerMap" metricKey="prdsafe/qwen-coder-1-5b-instruct" type="KPA" spec={"scaleTargetRef":{"kind":"Deployment","namespace":"prdsafe","name":"qwen-coder-1-5b-instruct","apiVersion":"apps/v1"},"minReplicas":1,"maxReplicas":4,"metricsSources":[{"metricSourceType":"pod","protocolType":"http","path":"metrics","port":"8080","targetMetric":"time_per_output_token_seconds_sum","targetValue":"10000"}],"scalingStrategy":"KPA"}
I0312 11:29:43.551825       7 kpa.go:309] "Begin panicking." panicTime="2025-03-12 11:29:43.551651146 +0000 UTC m=+703660.398055859"
I0312 11:29:43.551868       7 kpa.go:330] "Operating in panic mode." desiredPodCount=2 desiredPanicPodCount=2
I0312 11:29:43.551900       7 kpa.go:336] "Increasing pods count." originalPodCount=1 desiredPodCount=2
I0312 11:29:43.560204       7 podautoscaler_controller.go:486] "Successfully rescaled" PodAutoscaler="prdsafe/qwen-coder-1-5b-instruct-scale-time" currentReplicas=1 desiredReplicas=2 reason="time_per_output_token_seconds_sum above target"
I0312 11:29:43.580759       7 kpa.go:330] "Operating in panic mode." desiredPodCount=2 desiredPanicPodCount=2
I0312 11:29:44.777092       7 kpa.go:330] "Operating in panic mode." desiredPodCount=2 desiredPanicPodCount=2
E0312 11:29:54.773077       7 controller.go:316] "msg"="Reconciler error" "error"="failed to update metrics for scale target reference: failed to parse metrics from source http://10.163.193.9:8080/metrics: metrics time_per_output_token_seconds_sum not found" "PodAutoscaler"={"name":"qwen-coder-1-5b-instruct-scale-time","namespace":"prdsafe"} "controller"="podautoscaler" "controllerGroup"="autoscaling.aibrix.ai" "controllerKind"="PodAutoscaler" "name"="qwen-coder-1-5b-instruct-scale-time" "namespace"="prdsafe" "reconcileID"="d06271a2-5b4f-4ef3-a09c-7a7aef84a8e1"

### Use Case

```
apiVersion: autoscaling.aibrix.ai/v1alpha1
kind: PodAutoscaler
metadata:
  name: qwen-coder-1-5b-instruct-scale-time
  namespace: prdsafe
  labels:
    app.kubernetes.io/name: aibrix
  annotations:
    kpa.autoscaling.aibrix.ai/scale-down-delay: 2m
spec:
  scalingStrategy: KPA
  minReplicas: 1
  maxReplicas: 4
  metricsSources:
    - metricSourceType: pod
      protocolType: http
      port: '8080'
      path: metrics
      targetMetric: time_per_output_token_seconds_sum
      targetValue: '10000'
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: qwen-coder-1-5b-instruct
    namespace: prdsafe
```
