### ISSUE TITLE
kv cache deploy the model across different GPUs, it create two etcd pod!

### ISSUE THREAD

**Issue by ying2025** [vllm-project/aibrix#910]
### 🚀 Feature Description and Motivation

Heterogeneous GPU test `kv cache` , and it create two etcd.

### Use Case

I deploy two deployment on two machine, one in a100, another in t4.I create two kv-cache with different name.
```
kind: KVCache
metadata:
  name: deepseek-coder-7b-kvcache-t4
  namespace: prdsafe
  annotations:
    kvcache.orchestration.aibrix.ai/pod-affinity-workload: deepseek-coder-7b-instruct
    kvcache.orchestration.aibrix.ai/node-affinity-gpu-type: T4
    kvcache.orchestration.aibrix.ai/node-affinity-key: "nvidia.com/gpu.product"
```
```
kind: KVCache
metadata:
  name: deepseek-coder-7b-kvcache
  namespace: prdsafe
  annotations:
    kvcache.orchestration.aibrix.ai/pod-affinity-workload: deepseek-coder-7b-instruct
    kvcache.orchestration.aibrix.ai/node-affinity-gpu-type: A100
    kvcache.orchestration.aibrix.ai/node-affinity-key: "nvidia.com/gpu.product"
```
