### ISSUE TITLE
Failed to run RayFleet when using hostNetwork

### ISSUE THREAD

**Issue by vaaandark** [vllm-project/aibrix#915]
### 🐛 Describe the bug

When I was using hostNetwork to set up AIBrix DeepSeek R1 workload, it failed to connect to the Ray cluster. So I turn to set up without RDMA.

The ray worker:
```console
$ kubectl logs -f deepseek-r1-5cdb9559b5-mtfnv-worker-group-worker-4x5mt -c wait-gcs-ready
46 seconds elapsed: Waiting for GCS to be ready.
92 seconds elapsed: Waiting for GCS to be ready.
136 seconds elapsed: Waiting for GCS to be ready.
[2025-03-27 23:40:57,068 E 282 282] gcs_rpc_client.h:179: Failed to connect to GCS at address deepseek-r1-5cdb9559b5-mtfnv-head-svc.default.svc.cluster.local:6379 within 5 seconds.
[2025-03-27 23:41:27,070 W 282 282] gcs_client.cc:178: Failed to get cluster ID from GCS server: TimedOut: Timed out while waiting for GCS to become available.
Traceback (most recent call last):
  File "/usr/local/bin/ray", line 10, in <module>
    sys.exit(main())
             ^^^^^^
......
```

The header cannot find the other node:
```console
$ kubectl exec -it deepseek-r1-5cdb9559b5-mtfnv-head-t4c4v /bin/bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
# ray status
======== Autoscaler status: 2025-03-27 23:44:40.014845 ========
Node status
---------------------------------------------------------------
Active:
 1 node_bed19c6909580cb7646d7ff2d39a52deaed698abbf7a53354d290af9
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 0.0/192.0 CPU
 0.0/8.0 GPU
 0B/1.62TiB memory
 0B/186.26GiB object_store_memory

Demands:
 {'GPU': 1.0, 'node:10.32.5.221': 0.001} * 1, {'GPU': 1.0} * 15 (PACK): 1+ pending placement groups
```

### Steps to Reproduce

https://github.com/vllm-project/aibrix/blob/main/samples/deepseek-r1/deepseek-r1-ai-runtime.yaml

The differences I made from upon yaml:
- migrated the RDMA configuration from volcano engine to tencent cloud
- removed init containers, and used nfs to store model
- **used HostNetwork**

```yaml
apiVersion: orchestration.aibrix.ai/v1alpha1
kind: RayClusterFleet
metadata:
  labels:
    app.kubernetes.io/name: aibrix
    model.aibrix.ai/name: deepseek-r1
    model.aibrix.ai/port: "8000"
  name: deepseek-r1
spec:
  replicas: 1
  selector:
    matchLabels:
      model.aibrix.ai/name: deepseek-r1
      model.aibrix.ai/port: "8000"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        model.aibrix.ai/name: deepseek-r1
        model.aibrix.ai/port: "8000"
      annotations:
        ray.io/overwrite-container-cmd: "true"
    spec:
      rayVersion: '2.40.0'
      headGroupSpec:
        rayStartParams:
          dashboard-host: '0.0.0.0'
          block: 'false'
        template:
          metadata:
            labels:
              model.aibrix.ai/name: deepseek-r1
              model.aibrix.ai/port: "8000"
            annotations:
              tke.cloud.tencent.com/networks: "tke-route-eni,tke-rdma-ipvlan"
          spec:
            containers:
            - name: ray-head
              image: aibrix/vllm-openai:v0.7.3.self.post1
              ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: service
              command: ["/bin/bash", "-lc", "--"]
              args: ["ulimit -n 65536; echo head; $KUBERAY_GEN_RAY_START_CMD; vllm serve /data/$LLM_MODEL --served-model-name $LLM_MODEL --trust-remote-code --tensor-parallel-size 16 --distributed-executor-backend ray --uvicorn-log-level warning"]
              env:
              - name: LLM_MODEL
                value: deepseek-ai/DeepSeek-R1
              - name: GLOO_SOCKET_IFNAME
                value: eth0
              - name: NCCL_SOCKET_IFNAME
                value: eth0
              - name: NCCL_IB_DISABLE
                value: "0"
              - name: NCCL_IB_HCA
                value: mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1,mlx5_8:1
              resources:
                limits:
                  nvidia.com/gpu: 8
                  tke.cloud.tencent.com/tke-shared-rdma: 1
                requests:
                  nvidia.com/gpu: 8
                  tke.cloud.tencent.com/tke-shared-rdma: 1
              securityContext:
                capabilities:
                  add:
                  - IPC_LOCK
              startupProbe:
                httpGet:
                  path: /metrics
                  port: service
                initialDelaySeconds: 180
                failureThreshold: 150
                periodSeconds: 10
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /dev/shm
                  name: shared-mem
                - mountPath: /data
                  name: data
            hostNetwork: true
            volumes:
              - name: shared-mem
                emptyDir:
                  medium: Memory
              - name: data
                persistentVolumeClaim:
                 claimName: ai-model
      workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 1
        groupName: worker-group
        rayStartParams: {}
        template:
          metadata:
            labels:
              model.aibrix.ai/name: deepseek-r1
              model.aibrix.ai/port: "8000"
            annotations:
              tke.cloud.tencent.com/networks: "tke-route-eni,tke-rdma-ipvlan"
          spec:
            containers:
            - name: ray-worker
              image: aibrix/vllm-openai:v0.7.3.self.post1
              command: ["/bin/bash", "-lc", "--"]
              args: ["ulimit -n 65536; echo head; $KUBERAY_GEN_RAY_START_CMD;"]
              env:
              - name: LLM_MODEL
                value: deepseek-ai/DeepSeek-R1
              - name: GLOO_SOCKET_IFNAME
                value: eth0
              - name: NCCL_SOCKET_IFNAME
                value: eth0
              - name: NCCL_IB_DISABLE
                value: "0"
              - name: NCCL_IB_HCA
                value: mlx5_1:1,mlx5_2:1,mlx5_3:1,mlx5_4:1,mlx5_5:1,mlx5_6:1,mlx5_7:1,mlx5_8:1
              lifecycle:
                preStop:
                  exec:
                    command: [ "/bin/sh","-c","ray stop" ]
              resources:
                limits:
                  nvidia.com/gpu: 8
                  tke.cloud.tencent.com/tke-shared-rdma: 1
                requests:
                  nvidia.com/gpu: 8
                  tke.cloud.tencent.com/tke-shared-rdma: 1
              securityContext:
                capabilities:
                  add:
                    - IPC_LOCK
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /dev/shm
                  name: shared-mem
                - mountPath: /data
                  name: data
            hostNetwork: true
            volumes:
              - name: shared-mem
                emptyDir:
                  medium: Memory
              - name: data
                persistentVolumeClaim:
                  claimName: ai-model
```

### Expected behavior

Set up it correctly.

### Environment

- aibrix/vllm-openai:v0.7.3.self.post1
- kubernetes 1.30
- cloud provider: tencent cloud
