### ISSUE TITLE
RayClusterFleet HPA reports：unable to get the target's current scale

### ISSUE THREAD

**Issue by zhixian82** [vllm-project/aibrix#986]
### 🐛 Describe the bug

I create a RayClusterFleet and PodAutoscaler, and HPA was created as expected, but hpa  has an error condition: "the HPA controller was unable to get the target's current scale: rayclusterfleets.orchestration.aibrix.ai "qwen-coder-7b-instruct" not found"

### Steps to Reproduce

1. create rayclusterfleet by yaml like:

```
apiVersion: orchestration.aibrix.ai/v1alpha1
kind: RayClusterFleet
metadata:
  labels:
    model.aibrix.ai/name: qwen-coder-7b-instruct
    model.aibrix.ai/port: "8000"
    app.kubernetes.io/name: aibrix
    app.kubernetes.io/managed-by: kustomize
  name: qwen-coder-7b-instruct
spec:
  replicas: 2
  selector:
    matchLabels:
      model.aibrix.ai/name: qwen-coder-7b-instruct
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        model.aibrix.ai/name: qwen-coder-7b-instruct
        model.aibrix.ai/port: "8000"
      annotations:
        ray.io/overwrite-container-cmd: "true"
    spec:
      rayVersion: '2.10.0' # should match the Ray version in the image of the containers
      headGroupSpec:
        rayStartParams:
          dashboard-host: '0.0.0.0'
        template:
          metadata:
            labels:
              model.aibrix.ai/name: qwen-coder-7b-instruct
              model.aibrix.ai/port: "8000"
          spec:
            volumes:
            containers:
            - name: ray-head
              image: vllm/vllm-openai:v0.7.1
              ports:
              - containerPort: 6379
                name: gcs-server
              - containerPort: 8265
                name: dashboard
              - containerPort: 10001
                name: client
              - containerPort: 8000
                name: service
              command: [ "/bin/bash", "-c", "--" ]
              args:
              - >
                ulimit -n 65536 

                vllm serve Qwen/Qwen2.5-Coder-7B-Instruct \
                  --served-model-name qwen-coder-7b-instruct \
                  --tensor-parallel-size 1 \
                  --host 0.0.0.0 \
                  --port 8000 \
                  --dtype half
               resources:
                  limits:
                    cpu: "8000m"
                    nvidia.com/gpu: 2
                  requests:
                    cpu: "8000m"
                    nvidia.com/gpu: 2
```

2. create PodAutoscaler:
```
apiVersion: autoscaling.aibrix.ai/v1alpha1
kind: PodAutoscaler
metadata:
  name: qwen-coder-7b-instruct
  labels:
    app.kubernetes.io/name: aibrix
spec:
  scalingStrategy: HPA
  minReplicas: 1
  maxReplicas: 4
  metricsSources:
    - metricSourceType: pod
      protocolType: http
      port: '8000'
      path: metrics
      targetMetric: cpu
      targetValue: '30'
  scaleTargetRef:
    apiVersion: orchestration.aibrix.ai/v1alpha1
    kind: RayClusterFleet
    name: qwen-coder-7b-instruct
```

3. describe hpa and found an error:

```
[root@test distributed]# kubectl describe hpa qwen-coder-7b-instruct-hpa  
Name:                                                  qwen-coder-7b-instruct-hpa
Namespace:                                          default
Labels:                                                app.kubernetes.io/name=aibrix
Annotations:                                           <none>
Reference:                                             RayClusterFleet/qwen-coder-7b-instruct
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 30%
Min replicas:                                          1
Max replicas:                                          4
RayClusterFleet pods:                                  0 current / 0 desired
Conditions:
  Type         Status  Reason          Message
  ----         ------  ------          -------
  AbleToScale  False   FailedGetScale  the HPA controller was unable to get the target's current scale: rayclusterfleets.orchestration.aibrix.ai "qwen-coder-7b-instruct" not found
Events:
  Type     Reason          Age                   From                       Message
  ----     ------          ----                  ----                       -------
  Warning  FailedGetScale  3m31s (x41 over 13m)  horizontal-pod-autoscaler  rayclusterfleets.orchestration.aibrix.ai "qwen-coder-7b-instruct" not found

```

### Expected behavior

The HPA is working normally without any errors.

### Environment

- Aibrix version： 0.2.1
- k8s environment： 1.29
