### ISSUE TITLE
Error when installing AIBrix on arm64 Kubernetes cluster

### ISSUE THREAD

**Issue by omerap12** [vllm-project/aibrix#996]
### 🐛 Describe the bug

When installing AIBrix on arm64 Kubernetes cluster using the steps in the docs:
https://aibrix.readthedocs.io/latest/getting_started/installation/installation.html#install-aibrix-on-cloud
I get the following error:
```bash
k logs -n aibrix-system aibrix-controller-manager-5948f8f8b7-9sp56 
exec /manager: exec format error
```
My instance info:
```yaml
OS Image:                   Bottlerocket OS 1.36.0 (aws-k8s-1.32)
Operating System:           linux
Architecture:               arm64
```

Looks like the container image might not support arm64. I'm just getting started with AIBrix, so I’m not sure if this is expected.

If AIBrix only works on amd64, maybe it would be helpful to mention that in the docs. If it's supposed to support arm64 too, maybe the image needs to be built for multiple architectures.
Ill be glad to help with both :)

### Steps to Reproduce

1. Deploy AIBrix using the instructions from the official docs:  
   https://aibrix.readthedocs.io/latest/getting_started/installation/installation.html#install-aibrix-on-cloud-kubernetes-clusters  
2. Ensure that all pods are scheduled on `arm64` nodes.

### Expected behavior

Pods should be in Running state.

### Environment

eks - 1.32 k8s version
